- .github/workflows/build.yml
- bin/upload-artifacts
here's a dry-run of this \o/ https://github.com/getsentry/pypi/runs/7640335802?check_suite_focus=true
> upload built wheels and index to gcp

- packages.ini
I needed wheel and pip to build pyproject.toml things from source -- but figured I'd also do pip-tools while I'm at it
> add pip-tools

- packages.ini
via `python3 -m add_pkg -- -r../sentry/requirements-dev.txt` and `python3 -m add_pkg -- -r../sentry/requirements-dev-only-frozen.txt` -- against this PR: https://github.com/getsentry/sentry/pull/37608
> import requirements-dev from sentry

- build.py
- tests/build_test.py
google-crc32c has some complicated build requirements which I'll add later -- but for now I wanted to make sure we don't accidentally add other packages which may have this problem as well
> prevent adding likely pure-python cffi modules

- build.py
- packages.ini
this was getting a little bit noisy
> skip output for already existing packages

- build.py
- packages.ini
- tests/build_test.py
this was annoying me a bit so I decided to speed it up
```console
$ best-of -n 20 -- env BUILD_IN_CONTAINER=1 python -m build --pypi-url https://pypi.devinfra.sentry.io
....................
best of 20: 5.297s
```
```console
$ best-of -n 20 -- env BUILD_IN_CONTAINER=1 python -m build --pypi-url https://pypi.devinfra.sentry.io
....................
best of 20: 0.311s
```
> speed up noop case by 17x

- build.py
- packages.ini
these are the deps of `getsentry/pypi` itself -- not that it should depend on itself but to ease development
> add pypi deps

- packages.ini
This PR won't build without it: https://github.com/getsentry/sentry/pull/38490
> add psycopg-types library

- packages.ini
automated with `python -m upgrade_all`
> upgrade packages to latest versions

- packages.ini
edit: Just gonna ship this without salt==3005 since there's currently no mechanism to publish to internal pypi (since we'd wanna avoid public registry for these kinds of things), and Anthony has a few designs in mind. For now in ops I'm just gonna have people install a manually built salt wheel.
> feat: getsentry/salt@v3005-sentry-pypi for ops

- packages.ini
This PR: https://github.com/getsentry/snuba/pull/3185 requires this package
> Add jsonschema2md==0.4.0 for snuba docs

- packages.ini
automated with:
```bash
python3 -m add_pkg -- -r../sentry/requirements-dev.txt
```
> upgrade sentry dev packages

- add_pkg.py
- setup.cfg
Reverts getsentry/pypi#90
I'm going to factor `packaging` out of that script instead
> Revert "improve new-user ergonomics"

- packages.ini
I'd like to improve the type checking
> add some types-* packages 

- packages.ini
going to give this library a second chance -- last I tried it it didn't quite do what I wanted but maybe I can "fix" it enough to be usable in sentry
> add django-stubs

- docker/install-pythons
step 1 to building wheels for python 3.11
> add python 3.11 to the image

- packages.ini
> add setuptools-rust

- docker/Dockerfile
> add python3.11 to PATH in docker

- .github/workflows/build.yml
> Revert "remove gcloud utils install"

- packages.ini
Needs https://github.com/getsentry/publish/issues/1605
> Add Arroyo 2.0.0

- packages.ini
> add pytest-localserver

- packages.ini
Needs https://github.com/getsentry/publish/issues/1663
> Arroyo 2.3.0

- packages.ini
Contains a bug fix for search issues.
> ref(search-issues) Add new Snuba SDK version

- docker/requirements.in
- docker/requirements.txt
closes #150
closes #151
simpler to do this in one patch rather than two
> upgrade wheel and setuptools

- add_pkg.py
- tests/add_pkg_test.py
this will make it easier to automate this with `craft`
> add_pkg: support multiple packages and skipping resolution

- packages.ini
this fixes incompatibilities with the latest `wheel`
> add latest version of delocate

- docker/requirements.in
- docker/requirements.txt
> upgrade delocate for macos building to fix wheel incompatibility

- .github/workflows/auto-merge.yml
when commits are made by the github actions user then they are skipped by github actions
> auto-merge as a user

- packages.ini
trying to figure out an interaction between this and sentry-sdk
> add latest version of structlog

- packages.ini
works around some poetry breakage https://github.com/python-poetry/poetry-core/pull/542
> add latest isort

- packages.ini
Pre-requisite for resolving https://github.com/getsentry/sentry/security/dependabot/138
> add cryptography 39.0.1

- packages.ini
I want upgraded mypy -- figured I'd do the rest while I'm here
> upgrade sentry dev dependencies

- packages.ini
Refs https://github.com/getsentry/sentry/pull/45298
> feat: add openai

- packages.ini
we are using this at https://github.com/getsentry/snuba/pull/3871 -- we are somewhat far from productionizing the dependent code though
> ref: Add maturin

- packages.ini
Adding a new Croniter package to fix this:
https://github.com/getsentry/sentry/pull/49145
https://pypi.org/project/croniter/#toc-entry-20
> ref(crons): Upgrade Croniter

- docker/install-pythons
should fix the jsonnet issues in #332
> ensure specific versions of pip, setuptools, wheel

- packages.ini
Add the latest version of google-api-python-client
> Add google-api-python-client

- packages.ini
> add latest mmh3

- packages.ini
> add latest cssselect

- packages.ini
> Update OpenAI to 0.27.8

- packages.ini
> add the latest version of pydantic

- packages.ini
Pre-requisites to resolve https://github.com/getsentry/sentry/security/dependabot/162
> update grpcio and grpcio-status

- packages.ini
```
python3 -m add_pkg flask flask==2.2.5
```
> add flask 2.2.5

- packages.ini
Prerequisite work for https://github.com/getsentry/sentry/security/dependabot/113
> add newer versions of pillow

- packages.ini
a faster freezegun -- want to see how much impact it would have on the testsuite
freezegun appears to be unmaintained as well -- the primary maintainer doesn't seem interested in supporting it
> add time-machine

- packages.ini
```
python3 -m add_pkg reportlab==3.6.13
```
> add reportlab 3.6.13

- packages.ini
Adding google-cloud-kms to our package repository to support encryption efforts in the product.
> add google-cloud-kms package

- packages.ini
> add latest lxml

- packages.ini
this is needed for 3.11 compatibility
> add latest pyuwsgi

- packages.ini
hoping to do smaller hops in upgrading
> add latest patch versions of each minor celery version

- packages.ini
this is needed for 3.10 compatibility
> add latest version of reportlab

- packages.ini
upgrade OpenAI SDK to latest version. See https://github.com/getsentry/sentry/pull/60699
> upgrade openai sdk

- packages.ini
trying to phase out six as much as possible
> add upgraded versions of packages which depend on six

- packages.ini
Add [flake8-logging](https://github.com/adamchainz/flake8-logging).
See https://github.com/getsentry/sentry/pull/60850
> add flake8-logging

- packages.ini
this removes dependence on pkg_resources
> add latest googleapis-common-protos

- packages.ini
might allow us to upgrade urllib3
> add latest boto3

- packages.ini
this version fixes a warning in python 3.11
> add latest cssutils

- packages.ini
> add latest pillow version

- .github/workflows/build.yml
- docker/Dockerfile
- docker/install-pythons
> use indygreg pythons again, again

- packages.ini
> add google-cloud-secret-manager==2.15.0

- docker/requirements.in
- docker/requirements.txt
this allows validate to succeed in python 3.12
> upgrade virtualenv

- packages.ini
https://github.com/getsentry/salt/commit/516064a89cfcb803aff584a08cfffe59d149f27c
> add sentry-salt-3006.6 dependencies

- packages.ini
> add latest version of msgpack

- packages.ini
> add latest version of hiredis

- packages.ini
at least for https://github.com/advisories/GHSA-xxj9-f6rv-m3x4
> add django 5.0.2

- packages.ini
required for https://github.com/getsentry/relay/pull/3044
> add opentelemetry-proto=1.22.0

- packages.ini
To resolve https://github.com/getsentry/sentry/security/dependabot/233 and https://github.com/getsentry/sentry/security/dependabot/224
> add cryptography 42.0.4

- packages.ini
https://github.com/mozilla/django-csp/releases/tag/3.8
```
python3 -m add_pkg django-csp==3.8
```
> add django-csp 3.8

- packages.ini
another package using legacy namespace packages
> add latest google-cloud-spanner

- packages.ini
> add latest version of django

- packages.ini
See https://github.com/getsentry/relay/security/dependabot/82, https://github.com/getsentry/relay/pull/3316.
> Add black version 24.3.0

- packages.ini
Required for running an experiment on S4S
Ref: https://github.com/getsentry/team-processing/issues/135
> feat: add pylibmc@1.6.3

- packages.ini
To resolve https://github.com/getsentry/sentry/security/dependabot/242
> add pillow 10.3.0

- packages.ini
https://pypi.org/project/pytest-json-report/
> Adding pytest-json-report

- packages.ini
Updates datadog to latest version.
> chore: update datadog to v0.49.1

- packages.ini
Resolve https://github.com/getsentry/sentry/security/dependabot/244
> add idna 3.7

- packages.ini
See https://github.com/getsentry/relay/pull/3559
> chore: Add flask 3.0.3

- packages.ini
We're planning on using this to check cross-region RPC methods for breaking changes.
Refs getsentry/sentry#68337
> chore: Add openapi-pydantic 0.4.0

- packages.ini
Updates Maturin to latest version
> chore: update maturin to v1.5.1

- packages.ini
the current version causes weird pytest crashes in rare cases
> add latest version of trio

- packages.ini
this is a much smaller (and more permissively licensed) alternative to pycountry
some slight differences in country codes:
(`old` being the version currently in `sentry`, `new` being the latest pycountry on pypi):
```diff
--- ../sentry/new	2024-05-23 14:30:56
+++ iso3166	2024-05-23 15:00:30
@@ -37,7 +37,7 @@
BZ	Belize
CA	Canada
CC	Cocos (Keeling) Islands
-CD	Congo, The Democratic Republic of the
+CD	Congo, Democratic Republic of the
CF	Central African Republic
CG	Congo
CH	Switzerland
@@ -74,7 +74,7 @@
FO	Faroe Islands
FR	France
GA	Gabon
-GB	United Kingdom
+GB	United Kingdom of Great Britain and Northern Ireland
GD	Grenada
GE	Georgia
GF	French Guiana
@@ -230,10 +230,10 @@
UA	Ukraine
UG	Uganda
UM	United States Minor Outlying Islands
-US	United States
+US	United States of America
UY	Uruguay …
```
> add iso3166

- packages.ini
> add latest django-stubs-ext

- .github/workflows/build.yml
without this it downloads nothing silently!
> also upgrade download-artifact

- packages.ini
Added all the packages which are listed as requirements in sentry-infra-tools repository using `python -m add_pkg <pkg_name>`
> chore(packages): Add the packages needed by sentry infra tools

- packages.ini
Added the packages needed by the dev requirements of sentry infra tools. This will ensure that we can use sentry pypi url for dev as well.
> chore(packages): Add sentry infra tools dev packages

- packages.ini
fixes one of our last `pkg_resources` imports
> add latest version of honcho

- packages.ini
to better support rebuilding for 3.13
> add latest cython

- packages.ini
> Revert "Restrict sentry-jsonnet"

- packages.ini
Part of https://github.com/getsentry/sentry/issues/80208
> feat(crons): Add cronsim

- packages.ini
> add timelib 0.3.0

- packages.ini
first version with 3.13 wheels
> add rc1 for wrapt

- packages.ini
> add latest proto-plus

- packages.ini
this version fixes compatibility with 3.13
> add newer version of pydantic

- packages.ini
> add latest pydantic 1.x

- packages.ini
> add latest dependencies of celery

- packages.ini
This version has the fix for bytes warnings
Ref getsentry/getsentry#15583
> feat: Add h2==4.2.0

- packages.ini
I'd like to use the improved language version detection
> add latest pre-commit

- packages.ini
This adds newer versions for Flask, google-auth, and setuptools. 
and also introduces gunicorn.
> Add versions for several libraries

- .github/workflows/build.yml
- packages.ini
> Revert "fix: switch github actions to workload identity"

- packages.ini
Need a version `>=2.27.0` to access retry config on `read_row()`: https://github.com/googleapis/python-bigtable/issues/982
> OPS-6010: python3 -m add_pkg google-cloud-bigtable

- packages.ini
looking to codify our triggers in `getsentry`
> add django-pgtrigger

- make_index.py
- tests/make_index_test.py
see https://github.com/getsentry/pypi/pull/1569
> restore previous-package-list-json
