getsentry/pypi

.github/workflows/build.yml, .github/workflows/image.yml
tried this out in my scratch repo -- main branch commits run serially, PRs can run concurrently
=> serialize workflow runs of index build on the primary branch

packages.ini, tests/validate_test.py, validate.py
example output from architecture detection:
```
validating python3.10: dist/grpcio-1.46.3-cp310-cp310-macosx_10_10_universal2.whl
checking arch
-> grpc/_cython/cygrpc.cpython-310-darwin.so has mismatched architectures
---> you may be able to fix this with `ignore_wheels = grpcio-1.46.3-cp310-cp310-macosx_10_10_universal2.whl`
---> expected arm64, x86_64
---> received x86_64
```
=> add grpcio, forbid wheels with incorrect architectures

format_ini.py, tests/format_ini_test.py
this makes it much easier to resolve conflicts and paste a bunch of new packages
=> allow format_ini to remove duplicate names

README.md, build.py, format_ini.py, packages.ini, prebuild/crc32c, tests/build_test.py, tests/format_ini_test.py, validate.py
`crc32c` is a google project that isn't packaged for `apt` -- this mimicks the installation instructions here: https://github.com/googleapis/python-crc32c/blob/9be2d165b3ed7861e5329c305ab192d65b61b18f/scripts/manylinux/build_on_centos.sh
I needed to pick a newer version of `crc32c` as the one that was being used doesn't build on `arm64`
=> add build scripts for google-crc32c

packages.ini
this package has some special binary dependencies -- but fortunately the build scripts did their job!
```
=== maxminddb==2.0.3@(3, 8)
-> building...
Collecting maxminddb==2.0.3
Downloading maxminddb-2.0.3.tar.gz (286 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 286.1/286.1 kB 8.4 MB/s eta 0:00:00
Preparing metadata (setup.py): started
Preparing metadata (setup.py): finished with status 'done'
Saved /tmp/tmp_yqg407l/sdist/maxminddb-2.0.3.tar.gz
Successfully downloaded maxminddb
Looking in indexes: https://pypi.devinfra.sentry.io/simple
Processing /tmp/tmp_yqg407l/sdist/maxminddb-2.0.3.tar.gz
Preparing metadata (setup.py): started
Preparing metadata (setup.py): finished with status 'done'
Building wheels for collected packages: maxminddb
Building wheel for maxminddb (setup.py): started …
```
=> add maxminddb

build.py, packages.ini, tests/build_test.py
before this it was failing with:
```
=== google-cloud-pubsub==2.2.0@(3, 8)
-> building...
Traceback (most recent call last):
File "/opt/python/cp38-cp38/lib/python3.8/runpy.py", line 194, in _run_module_as_main
return _run_code(code, main_globals, None,
File "/opt/python/cp38-cp38/lib/python3.8/runpy.py", line 87, in _run_code
exec(code, run_globals)
File "/src/build.py", line 633, in <module>
raise SystemExit(main())
File "/src/build.py", line 620, in main
downloaded_wheel = _download(package, python, args.dest)
File "/src/build.py", line 398, in _download
arch_reason = _check_arch(filename_full)
File "/src/build.py", line 362, in _check_arch
archs_for_file = plat.get_archs(os.path.join(archdir, arch_file))
File "/src/build.py", line 280, in _linux_get_archs
raise …
```
=> ignore un-shebanged .py "scripts" in arch check

packages.ini, tests/validate_test.py, validate.py
cryptography has an incorrect `top_level.txt` due to a setuptools bug
=> ignore top_level.txt as it is not always accurate

packages.ini
Reverts getsentry/pypi#57
this doesn't actually remove the package -- but this package doesn't work properly
=> Revert "add uwsgi-dogstatsd-plugin"

runbook/deleting.md
in theory this works -- will try this out later for `uwsgi-dogstatsd-plugin` (not a security concern, but a failed experiment and will be good to exercise the runbook)
=> add runbook for deleting packages

packages.ini
This is the requirements.txt portion of https://github.com/getsentry/ops/pull/5255. No salt dependency which is a huge one.
=> feat: add ops requirements except salt

packages.ini
the latest version of this package comes with prebuilt wheels for the plat/arch pairs we care about so we no longer need special build instructions
=> add google-crc32c==1.5.0

packages.ini
sentry-sdk==1.9.9 had a bug with django signals (getsentry/sentry-python#1641) that is fixed in 1.9.10
=> Add sentry-sdk==1.9.10

tox.ini
rather than fixing `--devenv` for `skipsdist` (which _sometimes_ implies `skip_install` but not in `usedevelop` mode for historical reasons I don't understand) -- moving to `skip_install` seems to work
=> fix --devenv by using more specific skip_install

packages.ini
This also yanks 0.8.14 since it contained a regression in the normalize function.
=> Add sentry-relay 0.8.15

.github/workflows/pre-commit.yml, .github/workflows/test.yml
Committed via https://github.com/asottile/all-repos
=> ref: upgrade actions/setup-python to avoid set-output deprecation

build.py
noticed while poking at python 3.11
=> fix vendored distutils header paths on macos

packages.ini
Adding `cryptography` version `38.0.3` to resolve OpenSSL vulnerabilities. See https://github.com/pyca/cryptography/security/advisories/GHSA-39hc-v87j-747x.
=> add cryptography 38.0.3

.github/workflows/build.yml
github includes these by default
Committed via https://github.com/asottile/all-repos
=> remove gcloud utils install

packages.ini
This is now the min version for python profiling
=> Add sentry-sdk==1.11.0

.github/workflows/build.yml
apparently gsutil doesn't use `GOOGLE_APPLICATION_CREDENTIALS` unless explicitly logged in
tried this out on a test branch
=> fix gcloud auth by explicitly logging in

packages.ini
I think this fixes a hang I'm experiencing in pytest-xdist
=> add latest pytest and pytest-rerunfailures

packages.ini
Adds Django 3.2.16 to our package list.
=> add django lts 3.2.16

packages.ini
To support upgrade of `lxml`: https://github.com/getsentry/sentry/pull/45386.
=> python3-saml 1.15.0

packages.ini
```
$ python3 -m add_pkg django-csp django==2.2.28
resolving django-csp django==2.2.28...
[notice] A new release of pip available: 22.3.1 -> 23.1.2
[notice] To update, run: python3.11 -m pip install --upgrade pip
django==2.2.28: already present!
django-csp==3.7: adding...
pytz==2023.3: adding...
sqlparse==0.4.4: adding...
packages.ini: formatted
```
=> add django-csp 3.7

packages.ini
This adds `covdefaults` version 2.3.0, [as suggested by @asottile-sentry](https://github.com/getsentry/sentry/pull/51654#discussion_r1242869671), in order to get the `if TYPE_CHECKING` coverage exclusion. It will be added to `requirements-dev.txt` in `sentry` in a follow-up PR.
=> chore(deps): Add covdefaults 2.3.0

packages.ini
This failed before, so if this attempt fails we will instead add 1.0.5.
=> build: Build msgpack 1.0.4 for python 3.11

packages.ini
Removed incorrect python version constraint for 1.56.0.
=> grpcio supports 3.11

packages.ini
Newest milksnake, needed as a dependency for relay.
See https://github.com/getsentry/pypi/actions/runs/6667534528/job/18121888552?pr=478#step:5:9.
=> Update milksnake == 0.1.6

packages.ini
this is buildable / downloadable now
=> enable clickhouse-driver in 3.11+

packages.ini, prebuild/libxmlsec1-macos
xmlsec is incompatible with xmlsec1>=1.3 -- so we freeze to 1.2.x
I initially tried to do this through older brew versions but they were not linked properly for this version of macos -- so building it myself was easier
=> enable build of xmlsec on python 3.11

packages.ini
the old version of stripe vendors a copy of `six` which does not import in python 3.10
=> add newer versions of stripe

packages.ini
trying to pin down the breakage between the current version and 0.46 by trying a few intermediate versions
=> add newer datadog client

packages.ini
`python-memcached` is dead -- this seems like the most active alternative
=> ref: add pymemcache as a potential replacement for python-memcached

packages.ini
I'm hoping this unbreaks new-setuptools-building-git-archives in `getsentry` on python 3.10+
=> upgrade pip to latest

packages.ini
this is needed to build newer versions of lazy-object-proxy
=> add latest setuptools-scm

packages.ini
Bumping flake8-logging to 1.5.0 to include fix for 
```python
KeyError "Attempt to overwrite 'message' in LogRecord"
```
Changelog: https://github.com/adamchainz/flake8-logging/blob/main/CHANGELOG.rst#150-2024-01-23
Fix: https://github.com/adamchainz/flake8-logging/pull/77
=> chore(linting): update flake8-logging to 1.5.0 to include a fix

.github/workflows/build.yml, docker/Dockerfile, docker/install-pythons
I've validated locally that these build proper wheels on linux (where they were failing before)
=> use indygreg pythons again

README.md, build.py, tests/build_test.py
required for https://github.com/getsentry/pypi/pull/643 (which has this branch included for salt build to succeed), redo of #76
=> feat: likely_binary_ignore

packages.ini
slipcover is an alternative coverage tool that aims to be faster.  I'd like to see the impact on sentry's test times
=> add slipcover

packages.ini
this should finally allow us to purge `pytz`
=> add latest djangorestframework

packages.ini
this fixes a noisy warning in python 3.12
=> add the latest version of kombu

packages.ini
https://python-rapidjson.readthedocs.io/en/latest/benchmarks.html
I don't see any reason to use `rapidjson` after the benchmarks.
Ref: https://github.com/getsentry/team-processing/issues/145
=> chore: add orjson v3.10.0

.github/workflows/build.yml
github silently changed the architecture of macos-latest from intel to arm64
=> macos-latest -> macos-13

packages.ini
I'm looking to use this as part of a project I'm working on. It's a bit of a pain that it installs `requests` - I think it only uses that to download a new list from the public suffix list, which I will be disabling, so we don't really even need it.
=> Add tldextract package

packages.ini
We've got a good sized list of Dependabot alerts on getsentry/sentry. Adding these deps so that Dependabot can open PRs and get them resolved.
=> add latest version of deps to resolve dependabot alerts

packages.ini
This will be automated with craft in the future. I've gotten this release published to pypy.org.
=> Add first release for sentry-protos

packages.ini
something between pytest 8.0.0 and 8.3.2 is causing issues in sentry -- going to try and bump through the intermediates to hopefully pinpoint the regression
=> add intermediate versions of pytest

packages.ini
this latest version has fewer unnecessary runtime deps: https://github.com/googleapis/python-spanner/pull/1158
=> add latest google-cloud-spanner

packages.ini
Since I am porting over the sentry-infra-tools from the ops repo, I would like to ensure that I do not inadvertently break the tooling. In order to do that I would like to use the same dependencies which exist in the ops repo instead of using their latest versions.
Once we verify everything works correctly, we can think of upgrading the package versions.
=> fix(sentry-infra-tools): Use existing dependencies

packages.ini
This PR adds the packages which are needed by the ops repo but are not part of sentry infra tools. Adding these so that the venv created in ops repo can also use sentry pypi. These are basically the list from [here](https://github.com/getsentry/ops/blob/master/k8s/cli/requirements.in#L35-L47)
=> feat(ops): Add packages part of ops repo

packages.ini
also pulls in newer `nodeenv` which removes a dependence on deprecated `pkg_resources`
=> add latest version of pre-commit

.github/workflows/build.yml, docker/Dockerfile, docker/install-pythons
=> add python 3.13 pythons

build.py, packages.ini, tests/validate_test.py, validate.py
had to disable a lot of packages which either (1) didn't build or (2) produced purelib wheels when the rest were compiled -- will re-enable them in a followup
=> enable builds for python 3.13

packages.ini
We want to make use of being able to backdate timestamps for a metric we're writing, and this was introduced in 0.50.0
=> Bump datadog to 0.51.0

packages.ini
fixes a warning for NameConstant which will be removed in a future python version
=> add latest reportlab

packages.ini
fixes drift related to `DEFERRABLE` in migration squashes
=> add latest django-pg-zero-downtime-migrations

.github/workflows/build.yml, packages.ini
Switch `collect-and-deploy` job to workload identity. This will allow us to get rid of static GCP credentials `GOOGLE_APPLICATION_CREDENTIALS`.
=> fix: switch github actions to workload identity

packages.ini
We need this package to use a new gemini model (flash 2.0 lite) for user feedback spam detection. The old model `text-bison` has been removed so we need this to fix the feature.
The only new dependency is `websockets`. It's only used by the `google.genai.live` module which we won't be using. To resolve a dependency conflict with `anyio`, this also upgrades `openai` to latest.
=> add_pkg google-genai==1.13.0 and upgrade openai==1.77.0

packages.ini
Of course the name `anton-testing-deleteme-123` is not final. I just wanted to use a dummy name so in case something goes wrong we do not have a broken/abandoned package with a legit sounding sentry name on PyPI.
=> Added dummy package for testing gradual sdk rollout

packages.ini
We have some systems like super big consumers using python-rapidjson 1.20.
=> Update python-rapidjson to version 1.20

packages.ini
This fixes a path traversal vulnerability in PackageIndex.
See https://github.com/getsentry/relay/security/dependabot/106 for more info
=> chore(setuptools): Bump to the patched version: 78.1.1

packages.ini
Jumping to protobuf 6.31.1 has had a loooot of downstream impact, requiring a dozen other library version bumps. Going to break this up into smaller updates, first targeting the minimum version that resolves the vulnerability.
=> deps: protobuf 5.29.5

validate.py
building mkdocs-material (in https://github.com/getsentry/pypi/pull/1610) fails since the wheel ends up with py311-none-any tag - which afaict is within spec so we should do a broader compat check than == "py3"
anthony says "it's within spec but nothing should ever produce a wheel like this / why are we getting such a weird wheel?"
i'm not sure if it's a big deal - it _is_ within the spec
=> feat: less strict interpreter tag

packages.ini
`tokenizers` is used for tokenization of strings. While we do currently import titoken as well, we want to use `tokenizers` to count tokens the same way Seer does in Sentry for stacktrace token counts. We could consider converting usages of titoken to `tokenizers` to maintain a dependency on only one tokenization package, but for now we will have them both.
=> Add `tokenizers` package

packages.ini
Requirements taken from https://github.com/getsentry/launchpad/blob/main/requirements.txt.
In large part it is additional versions of existing packages however some of the notable additions are:
- lzfse - Apple compression format parsing
- asn1crypto - For parsing some app signatures
- pillow-heif  - .heif support for pillow
- lief - binary parsing (ELF, MachO, etc) library
Prerequisite for EME-213
=> Add packages used by getsentry/launchpad
